# Generated by Django 5.2 on 2025-04-25 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movie_poster_image_movie_poster_viewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_genre2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_movie2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_movie3',
        ),
    ]
