# Generated by Django 5.2 on 2025-04-25 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_userprofile_favorite_genre2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='favorite_genre1',
            new_name='favorite_genre',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='favorite_movie1',
            new_name='favorite_movie',
        ),
    ]
