# Generated by Django 5.2 on 2025-04-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_favorite_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='favorite_genre',
            new_name='favorite_genre1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='favorite_movie',
            new_name='favorite_movie1',
        ),
    ]
